# Generated by Django 5.2 on 2025-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contac',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
